Extension { #name : 'GncLeaf' }

{ #category : '*Ume' }
GncLeaf >> allChildAtLevel: level currentLevel: currentLevel [

	^ ( level = currentLevel ) ifTrue: [ OrderedCollection with: self ] ifFalse: [ {} ]
]

{ #category : '*Ume' }
GncLeaf >> allChildren [

	^ #(  )
]

{ #category : '*Ume' }
GncLeaf >> asPharoObject [

	^ self asPrimitiveObject 
]

{ #category : '*Ume' }
GncLeaf >> backPropagateToChildren: reward [

	"Do nothing, it's a leaf"
]

{ #category : '*Ume' }
GncLeaf >> backPropagateToChildren: reward level: level [

	"Do nothing, it's a leaf"
]

{ #category : '*Ume' }
GncLeaf >> isTypeVariable [

	^ token class = ByteString and: [ token last = $: ]
]

{ #category : '*Ume' }
GncLeaf >> token [

	^ token
]

{ #category : '*Ume' }
GncLeaf >> varName [

	^ token allButLast
]
