Extension { #name : 'GncRule' }

{ #category : '*Ume' }
GncRule >> backPropagate: bla [

	"TODO: delete me"
]

{ #category : '*Ume' }
GncRule >> reward [

	"DELETE ME"
]

{ #category : '*Ume' }
GncRule >> utc: totalVisits by: c [

	"DELETE ME"
]

{ #category : '*Ume' }
GncRule >> visit [

	"TODO: delete me"
]

{ #category : '*Ume' }
GncRule >> visited [

	"todo: delete me"
]

{ #category : '*Ume' }
GncRule >> visits [

	"todo: delete me"
]
